apiVersion: upm.syntropycloud.io/v1alpha1
kind: GrpcCall
metadata:
  name: clickhouse-set-variable-runtime
  namespace: upm-clickhouse-runtime
spec:
  targetUnit: clickhouse-runtime-0
  type: clickhouse
  action: set-variable
  ttlSecondsAfterFinished: 3600
  parameters:
    username: default
    key: max_threads
    value: "8"
