global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/clickhouse
  tag: "26.3.9.8"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/clickhouse-agent
    tag: "26.3"
    pullPolicy: IfNotPresent
